# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Timeline' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Timeline
  pod 'R.swift'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'MBProgressHUD', '~> 1.2.0'

  target 'TimelineTests' do
    inherit! :search_paths
    # Pods for testing
  pod 'RxTest' 
  pod 'RxBlocking'
  end

end
